use super::*;#[repr(C)]
#[derive(Copy, Clone)]
pub(crate) struct Sqlite3QrfSpec {
    pub(crate) i_version: u8,
    pub(crate) e_style: u8,
    pub(crate) e_esc: u8,
    pub(crate) e_text: u8,
    pub(crate) e_title: u8,
    pub(crate) e_blob: u8,
    pub(crate) b_titles: u8,
    pub(crate) b_word_wrap: u8,
    pub(crate) b_text_jsonb: u8,
    pub(crate) e_dflt_align: u8,
    pub(crate) e_title_align: u8,
    pub(crate) b_split_column: u8,
    pub(crate) b_border: u8,
    pub(crate) n_wrap: i16,
    pub(crate) n_screen_width: i16,
    pub(crate) n_line_limit: i16,
    pub(crate) n_title_limit: i16,
    pub(crate) n_multi_insert: u32,
    pub(crate) n_char_limit: i32,
    pub(crate) n_width: i32,
    pub(crate) n_align: i32,
    pub(crate) a_width: *mut i16,
    pub(crate) a_align: *mut u8,
    pub(crate) z_column_sep: *mut i8,
    pub(crate) z_row_sep: *mut i8,
    pub(crate) z_table_name: *mut i8,
    pub(crate) z_null: *mut i8,
    pub(crate) x_render: Option<unsafe extern "C" fn(*mut (),
        *mut Sqlite3Value) -> *mut i8>,
    pub(crate) x_write: Option<unsafe extern "C" fn(*mut (), *const i8, i64)
        -> i32>,
    pub(crate) p_render_arg: *mut (),
    pub(crate) p_write_arg: *mut (),
    pub(crate) pz_output: *mut *mut i8,
}