#[unsafe(no_mangle)]
pub extern "C" fn sqlite3_opcode_name(i: i32) -> *const i8 {
    unsafe { return az_name[i as usize]; }
}
static mut az_name: [*const i8; 192] =
    [c"Savepoint".as_ptr() as *const i8, c"AutoCommit".as_ptr() as *const i8,
            c"Transaction".as_ptr() as *const i8,
            c"Checkpoint".as_ptr() as *const i8,
            c"JournalMode".as_ptr() as *const i8,
            c"Vacuum".as_ptr() as *const i8, c"VFilter".as_ptr() as *const i8,
            c"VUpdate".as_ptr() as *const i8, c"Init".as_ptr() as *const i8,
            c"Goto".as_ptr() as *const i8, c"Gosub".as_ptr() as *const i8,
            c"InitCoroutine".as_ptr() as *const i8,
            c"Yield".as_ptr() as *const i8,
            c"MustBeInt".as_ptr() as *const i8, c"Jump".as_ptr() as *const i8,
            c"Once".as_ptr() as *const i8, c"If".as_ptr() as *const i8,
            c"IfNot".as_ptr() as *const i8, c"IsType".as_ptr() as *const i8,
            c"Not".as_ptr() as *const i8, c"IfNullRow".as_ptr() as *const i8,
            c"SeekLT".as_ptr() as *const i8, c"SeekLE".as_ptr() as *const i8,
            c"SeekGE".as_ptr() as *const i8, c"SeekGT".as_ptr() as *const i8,
            c"IfNotOpen".as_ptr() as *const i8,
            c"IfNoHope".as_ptr() as *const i8,
            c"NoConflict".as_ptr() as *const i8,
            c"NotFound".as_ptr() as *const i8, c"Found".as_ptr() as *const i8,
            c"SeekRowid".as_ptr() as *const i8,
            c"NotExists".as_ptr() as *const i8, c"Last".as_ptr() as *const i8,
            c"IfSizeBetween".as_ptr() as *const i8,
            c"SorterSort".as_ptr() as *const i8,
            c"Sort".as_ptr() as *const i8, c"Rewind".as_ptr() as *const i8,
            c"IfEmpty".as_ptr() as *const i8,
            c"SorterNext".as_ptr() as *const i8,
            c"Prev".as_ptr() as *const i8, c"Next".as_ptr() as *const i8,
            c"IdxLE".as_ptr() as *const i8, c"IdxGT".as_ptr() as *const i8,
            c"Or".as_ptr() as *const i8, c"And".as_ptr() as *const i8,
            c"IdxLT".as_ptr() as *const i8, c"IdxGE".as_ptr() as *const i8,
            c"IFindKey".as_ptr() as *const i8,
            c"RowSetRead".as_ptr() as *const i8,
            c"RowSetTest".as_ptr() as *const i8,
            c"Program".as_ptr() as *const i8, c"IsNull".as_ptr() as *const i8,
            c"NotNull".as_ptr() as *const i8, c"Ne".as_ptr() as *const i8,
            c"Eq".as_ptr() as *const i8, c"Gt".as_ptr() as *const i8,
            c"Le".as_ptr() as *const i8, c"Lt".as_ptr() as *const i8,
            c"Ge".as_ptr() as *const i8, c"ElseEq".as_ptr() as *const i8,
            c"FkIfZero".as_ptr() as *const i8, c"IfPos".as_ptr() as *const i8,
            c"IfNotZero".as_ptr() as *const i8,
            c"DecrJumpZero".as_ptr() as *const i8,
            c"IncrVacuum".as_ptr() as *const i8,
            c"VNext".as_ptr() as *const i8, c"Filter".as_ptr() as *const i8,
            c"PureFunc".as_ptr() as *const i8,
            c"Function".as_ptr() as *const i8,
            c"Return".as_ptr() as *const i8,
            c"EndCoroutine".as_ptr() as *const i8,
            c"HaltIfNull".as_ptr() as *const i8,
            c"Halt".as_ptr() as *const i8, c"Integer".as_ptr() as *const i8,
            c"Int64".as_ptr() as *const i8, c"String".as_ptr() as *const i8,
            c"BeginSubrtn".as_ptr() as *const i8,
            c"Null".as_ptr() as *const i8, c"SoftNull".as_ptr() as *const i8,
            c"Blob".as_ptr() as *const i8, c"Variable".as_ptr() as *const i8,
            c"Move".as_ptr() as *const i8, c"Copy".as_ptr() as *const i8,
            c"SCopy".as_ptr() as *const i8, c"IntCopy".as_ptr() as *const i8,
            c"FkCheck".as_ptr() as *const i8,
            c"ResultRow".as_ptr() as *const i8,
            c"CollSeq".as_ptr() as *const i8, c"AddImm".as_ptr() as *const i8,
            c"RealAffinity".as_ptr() as *const i8,
            c"Cast".as_ptr() as *const i8,
            c"Permutation".as_ptr() as *const i8,
            c"Compare".as_ptr() as *const i8, c"IsTrue".as_ptr() as *const i8,
            c"ZeroOrNull".as_ptr() as *const i8,
            c"Offset".as_ptr() as *const i8, c"Column".as_ptr() as *const i8,
            c"TypeCheck".as_ptr() as *const i8,
            c"Affinity".as_ptr() as *const i8,
            c"MakeRecord".as_ptr() as *const i8,
            c"Count".as_ptr() as *const i8,
            c"ReadCookie".as_ptr() as *const i8,
            c"SetCookie".as_ptr() as *const i8,
            c"BitAnd".as_ptr() as *const i8, c"BitOr".as_ptr() as *const i8,
            c"ShiftLeft".as_ptr() as *const i8,
            c"ShiftRight".as_ptr() as *const i8, c"Add".as_ptr() as *const i8,
            c"Subtract".as_ptr() as *const i8,
            c"Multiply".as_ptr() as *const i8,
            c"Divide".as_ptr() as *const i8,
            c"Remainder".as_ptr() as *const i8,
            c"Concat".as_ptr() as *const i8,
            c"ReopenIdx".as_ptr() as *const i8,
            c"OpenRead".as_ptr() as *const i8,
            c"BitNot".as_ptr() as *const i8,
            c"OpenWrite".as_ptr() as *const i8,
            c"OpenDup".as_ptr() as *const i8,
            c"String8".as_ptr() as *const i8,
            c"OpenAutoindex".as_ptr() as *const i8,
            c"OpenEphemeral".as_ptr() as *const i8,
            c"SorterOpen".as_ptr() as *const i8,
            c"SequenceTest".as_ptr() as *const i8,
            c"OpenPseudo".as_ptr() as *const i8,
            c"Close".as_ptr() as *const i8,
            c"ColumnsUsed".as_ptr() as *const i8,
            c"SeekScan".as_ptr() as *const i8,
            c"SeekHit".as_ptr() as *const i8,
            c"Sequence".as_ptr() as *const i8,
            c"NewRowid".as_ptr() as *const i8,
            c"Insert".as_ptr() as *const i8, c"RowCell".as_ptr() as *const i8,
            c"Delete".as_ptr() as *const i8,
            c"ResetCount".as_ptr() as *const i8,
            c"SorterCompare".as_ptr() as *const i8,
            c"SorterData".as_ptr() as *const i8,
            c"RowData".as_ptr() as *const i8, c"Rowid".as_ptr() as *const i8,
            c"NullRow".as_ptr() as *const i8,
            c"SeekEnd".as_ptr() as *const i8,
            c"IdxInsert".as_ptr() as *const i8,
            c"SorterInsert".as_ptr() as *const i8,
            c"IdxDelete".as_ptr() as *const i8,
            c"DeferredSeek".as_ptr() as *const i8,
            c"IdxRowid".as_ptr() as *const i8,
            c"FinishSeek".as_ptr() as *const i8,
            c"Destroy".as_ptr() as *const i8, c"Clear".as_ptr() as *const i8,
            c"ResetSorter".as_ptr() as *const i8,
            c"CreateBtree".as_ptr() as *const i8,
            c"SqlExec".as_ptr() as *const i8,
            c"ParseSchema".as_ptr() as *const i8,
            c"LoadAnalysis".as_ptr() as *const i8,
            c"DropTable".as_ptr() as *const i8, c"Real".as_ptr() as *const i8,
            c"DropIndex".as_ptr() as *const i8,
            c"DropTrigger".as_ptr() as *const i8,
            c"IntegrityCk".as_ptr() as *const i8,
            c"RowSetAdd".as_ptr() as *const i8,
            c"Param".as_ptr() as *const i8,
            c"FkCounter".as_ptr() as *const i8,
            c"MemMax".as_ptr() as *const i8,
            c"OffsetLimit".as_ptr() as *const i8,
            c"AggInverse".as_ptr() as *const i8,
            c"AggStep".as_ptr() as *const i8,
            c"AggStep1".as_ptr() as *const i8,
            c"AggValue".as_ptr() as *const i8,
            c"AggFinal".as_ptr() as *const i8,
            c"Expire".as_ptr() as *const i8,
            c"CursorLock".as_ptr() as *const i8,
            c"CursorUnlock".as_ptr() as *const i8,
            c"TableLock".as_ptr() as *const i8,
            c"VBegin".as_ptr() as *const i8, c"VCreate".as_ptr() as *const i8,
            c"VDestroy".as_ptr() as *const i8, c"VOpen".as_ptr() as *const i8,
            c"VCheck".as_ptr() as *const i8, c"VInitIn".as_ptr() as *const i8,
            c"VColumn".as_ptr() as *const i8,
            c"VRename".as_ptr() as *const i8,
            c"Pagecount".as_ptr() as *const i8,
            c"MaxPgcnt".as_ptr() as *const i8,
            c"ClrSubtype".as_ptr() as *const i8,
            c"GetSubtype".as_ptr() as *const i8,
            c"SetSubtype".as_ptr() as *const i8,
            c"FilterAdd".as_ptr() as *const i8,
            c"Trace".as_ptr() as *const i8,
            c"CursorHint".as_ptr() as *const i8,
            c"ReleaseReg".as_ptr() as *const i8,
            c"Noop".as_ptr() as *const i8, c"Explain".as_ptr() as *const i8,
            c"Abortable".as_ptr() as *const i8];
extern "C" {
    fn __transpiler_isa(child: i32, ancestor: i32)
    -> bool;
}