use super::*;

/// Definitions of all built-in pragmas
#[repr(C)]
#[derive(Copy, Clone)]
pub(crate) struct PragmaName {
    pub(crate) z_name: *const i8,
    pub(crate) e_prag_typ: u8,
    pub(crate) m_prag_flg: u8,
    pub(crate) i_prag_c_name: u8,
    pub(crate) n_prag_c_name: u8,
    pub(crate) i_arg: u64,
}

pub(crate) static mut a_pragma_name: [PragmaName; 67] =
    [PragmaName {
                z_name: c"analysis_limit".as_ptr() as *const i8,
                e_prag_typ: 1 as u8,
                m_prag_flg: 16 as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"application_id".as_ptr() as *const i8,
                e_prag_typ: 2 as u8,
                m_prag_flg: (4 | 16) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 8 as u64,
            },
            PragmaName {
                z_name: c"auto_vacuum".as_ptr() as *const i8,
                e_prag_typ: 3 as u8,
                m_prag_flg: (1 | 16 | 128 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"automatic_index".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 32768 as u64,
            },
            PragmaName {
                z_name: c"busy_timeout".as_ptr() as *const i8,
                e_prag_typ: 5 as u8,
                m_prag_flg: 16 as u8,
                i_prag_c_name: 56 as u8,
                n_prag_c_name: 1 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"cache_size".as_ptr() as *const i8,
                e_prag_typ: 6 as u8,
                m_prag_flg: (1 | 16 | 128 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"cache_spill".as_ptr() as *const i8,
                e_prag_typ: 7 as u8,
                m_prag_flg: (16 | 128 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"case_sensitive_like".as_ptr() as *const i8,
                e_prag_typ: 8 as u8,
                m_prag_flg: 2 as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"cell_size_check".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 2097152 as u64,
            },
            PragmaName {
                z_name: c"checkpoint_fullfsync".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 16 as u64,
            },
            PragmaName {
                z_name: c"collation_list".as_ptr() as *const i8,
                e_prag_typ: 9 as u8,
                m_prag_flg: 16 as u8,
                i_prag_c_name: 33 as u8,
                n_prag_c_name: 2 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"compile_options".as_ptr() as *const i8,
                e_prag_typ: 10 as u8,
                m_prag_flg: 16 as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"count_changes".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: (1 as u64) << 32,
            },
            PragmaName {
                z_name: c"data_version".as_ptr() as *const i8,
                e_prag_typ: 2 as u8,
                m_prag_flg: (8 | 16) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 15 as u64,
            },
            PragmaName {
                z_name: c"database_list".as_ptr() as *const i8,
                e_prag_typ: 12 as u8,
                m_prag_flg: 16 as u8,
                i_prag_c_name: 50 as u8,
                n_prag_c_name: 3 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"default_cache_size".as_ptr() as *const i8,
                e_prag_typ: 13 as u8,
                m_prag_flg: (1 | 16 | 128 | 4) as u8,
                i_prag_c_name: 55 as u8,
                n_prag_c_name: 1 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"defer_foreign_keys".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 524288 as u64,
            },
            PragmaName {
                z_name: c"empty_result_callbacks".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 256 as u64,
            },
            PragmaName {
                z_name: c"encoding".as_ptr() as *const i8,
                e_prag_typ: 14 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"foreign_key_check".as_ptr() as *const i8,
                e_prag_typ: 15 as u8,
                m_prag_flg: (1 | 16 | 32 | 64) as u8,
                i_prag_c_name: 43 as u8,
                n_prag_c_name: 4 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"foreign_key_list".as_ptr() as *const i8,
                e_prag_typ: 16 as u8,
                m_prag_flg: (1 | 32 | 64) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 8 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"foreign_keys".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 16384 as u64,
            },
            PragmaName {
                z_name: c"freelist_count".as_ptr() as *const i8,
                e_prag_typ: 2 as u8,
                m_prag_flg: (8 | 16) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"full_column_names".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 4 as u64,
            },
            PragmaName {
                z_name: c"fullfsync".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 8 as u64,
            },
            PragmaName {
                z_name: c"function_list".as_ptr() as *const i8,
                e_prag_typ: 17 as u8,
                m_prag_flg: 16 as u8,
                i_prag_c_name: 15 as u8,
                n_prag_c_name: 6 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"hard_heap_limit".as_ptr() as *const i8,
                e_prag_typ: 18 as u8,
                m_prag_flg: 16 as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"ignore_check_constraints".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 512 as u64,
            },
            PragmaName {
                z_name: c"incremental_vacuum".as_ptr() as *const i8,
                e_prag_typ: 19 as u8,
                m_prag_flg: (1 | 2) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"index_info".as_ptr() as *const i8,
                e_prag_typ: 20 as u8,
                m_prag_flg: (1 | 32 | 64) as u8,
                i_prag_c_name: 27 as u8,
                n_prag_c_name: 3 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"index_list".as_ptr() as *const i8,
                e_prag_typ: 21 as u8,
                m_prag_flg: (1 | 32 | 64) as u8,
                i_prag_c_name: 33 as u8,
                n_prag_c_name: 5 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"index_xinfo".as_ptr() as *const i8,
                e_prag_typ: 20 as u8,
                m_prag_flg: (1 | 32 | 64) as u8,
                i_prag_c_name: 27 as u8,
                n_prag_c_name: 6 as u8,
                i_arg: 1 as u64,
            },
            PragmaName {
                z_name: c"integrity_check".as_ptr() as *const i8,
                e_prag_typ: 22 as u8,
                m_prag_flg: (1 | 16 | 32 | 64) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"journal_mode".as_ptr() as *const i8,
                e_prag_typ: 23 as u8,
                m_prag_flg: (1 | 16 | 128) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"journal_size_limit".as_ptr() as *const i8,
                e_prag_typ: 24 as u8,
                m_prag_flg: (16 | 128) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"legacy_alter_table".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 67108864 as u64,
            },
            PragmaName {
                z_name: c"lock_proxy_file".as_ptr() as *const i8,
                e_prag_typ: 25 as u8,
                m_prag_flg: 4 as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"locking_mode".as_ptr() as *const i8,
                e_prag_typ: 26 as u8,
                m_prag_flg: (16 | 128) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"max_page_count".as_ptr() as *const i8,
                e_prag_typ: 27 as u8,
                m_prag_flg: (1 | 16 | 128) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"mmap_size".as_ptr() as *const i8,
                e_prag_typ: 28 as u8,
                m_prag_flg: 0 as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"module_list".as_ptr() as *const i8,
                e_prag_typ: 29 as u8,
                m_prag_flg: 16 as u8,
                i_prag_c_name: 9 as u8,
                n_prag_c_name: 1 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"optimize".as_ptr() as *const i8,
                e_prag_typ: 30 as u8,
                m_prag_flg: (32 | 1) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"page_count".as_ptr() as *const i8,
                e_prag_typ: 27 as u8,
                m_prag_flg: (1 | 16 | 128) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"page_size".as_ptr() as *const i8,
                e_prag_typ: 31 as u8,
                m_prag_flg: (16 | 128 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"pragma_list".as_ptr() as *const i8,
                e_prag_typ: 32 as u8,
                m_prag_flg: 16 as u8,
                i_prag_c_name: 9 as u8,
                n_prag_c_name: 1 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"query_only".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 1048576 as u64,
            },
            PragmaName {
                z_name: c"quick_check".as_ptr() as *const i8,
                e_prag_typ: 22 as u8,
                m_prag_flg: (1 | 16 | 32 | 64) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"read_uncommitted".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: (4 as u64) << 32,
            },
            PragmaName {
                z_name: c"recursive_triggers".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 8192 as u64,
            },
            PragmaName {
                z_name: c"reverse_unordered_selects".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 4096 as u64,
            },
            PragmaName {
                z_name: c"schema_version".as_ptr() as *const i8,
                e_prag_typ: 2 as u8,
                m_prag_flg: (4 | 16) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 1 as u64,
            },
            PragmaName {
                z_name: c"secure_delete".as_ptr() as *const i8,
                e_prag_typ: 33 as u8,
                m_prag_flg: 16 as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"short_column_names".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 64 as u64,
            },
            PragmaName {
                z_name: c"shrink_memory".as_ptr() as *const i8,
                e_prag_typ: 34 as u8,
                m_prag_flg: 2 as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"soft_heap_limit".as_ptr() as *const i8,
                e_prag_typ: 35 as u8,
                m_prag_flg: 16 as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"synchronous".as_ptr() as *const i8,
                e_prag_typ: 36 as u8,
                m_prag_flg: (1 | 16 | 128 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"table_info".as_ptr() as *const i8,
                e_prag_typ: 37 as u8,
                m_prag_flg: (1 | 32 | 64) as u8,
                i_prag_c_name: 8 as u8,
                n_prag_c_name: 6 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"table_list".as_ptr() as *const i8,
                e_prag_typ: 38 as u8,
                m_prag_flg: (1 | 32) as u8,
                i_prag_c_name: 21 as u8,
                n_prag_c_name: 6 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"table_xinfo".as_ptr() as *const i8,
                e_prag_typ: 37 as u8,
                m_prag_flg: (1 | 32 | 64) as u8,
                i_prag_c_name: 8 as u8,
                n_prag_c_name: 7 as u8,
                i_arg: 1 as u64,
            },
            PragmaName {
                z_name: c"temp_store".as_ptr() as *const i8,
                e_prag_typ: 39 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"temp_store_directory".as_ptr() as *const i8,
                e_prag_typ: 40 as u8,
                m_prag_flg: 4 as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"threads".as_ptr() as *const i8,
                e_prag_typ: 41 as u8,
                m_prag_flg: 16 as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"trusted_schema".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 128 as u64,
            },
            PragmaName {
                z_name: c"user_version".as_ptr() as *const i8,
                e_prag_typ: 2 as u8,
                m_prag_flg: (4 | 16) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 6 as u64,
            },
            PragmaName {
                z_name: c"wal_autocheckpoint".as_ptr() as *const i8,
                e_prag_typ: 42 as u8,
                m_prag_flg: 0 as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"wal_checkpoint".as_ptr() as *const i8,
                e_prag_typ: 43 as u8,
                m_prag_flg: 1 as u8,
                i_prag_c_name: 47 as u8,
                n_prag_c_name: 3 as u8,
                i_arg: 0 as u64,
            },
            PragmaName {
                z_name: c"writable_schema".as_ptr() as *const i8,
                e_prag_typ: 4 as u8,
                m_prag_flg: (16 | 4) as u8,
                i_prag_c_name: 0 as u8,
                n_prag_c_name: 0 as u8,
                i_arg: (1 | 134217728) as u64,
            }];

/// Names of columns for pragmas that return multi-column result
///* or that return single-column results where the name of the
///* result column is different from the name of the pragma
pub(crate) static mut prag_c_name: [*const i8; 57] =
    [c"id".as_ptr() as *const i8, c"seq".as_ptr() as *const i8,
            c"table".as_ptr() as *const i8, c"from".as_ptr() as *const i8,
            c"to".as_ptr() as *const i8, c"on_update".as_ptr() as *const i8,
            c"on_delete".as_ptr() as *const i8,
            c"match".as_ptr() as *const i8, c"cid".as_ptr() as *const i8,
            c"name".as_ptr() as *const i8, c"type".as_ptr() as *const i8,
            c"notnull".as_ptr() as *const i8,
            c"dflt_value".as_ptr() as *const i8, c"pk".as_ptr() as *const i8,
            c"hidden".as_ptr() as *const i8, c"name".as_ptr() as *const i8,
            c"builtin".as_ptr() as *const i8, c"type".as_ptr() as *const i8,
            c"enc".as_ptr() as *const i8, c"narg".as_ptr() as *const i8,
            c"flags".as_ptr() as *const i8, c"schema".as_ptr() as *const i8,
            c"name".as_ptr() as *const i8, c"type".as_ptr() as *const i8,
            c"ncol".as_ptr() as *const i8, c"wr".as_ptr() as *const i8,
            c"strict".as_ptr() as *const i8, c"seqno".as_ptr() as *const i8,
            c"cid".as_ptr() as *const i8, c"name".as_ptr() as *const i8,
            c"desc".as_ptr() as *const i8, c"coll".as_ptr() as *const i8,
            c"key".as_ptr() as *const i8, c"seq".as_ptr() as *const i8,
            c"name".as_ptr() as *const i8, c"unique".as_ptr() as *const i8,
            c"origin".as_ptr() as *const i8, c"partial".as_ptr() as *const i8,
            c"tbl".as_ptr() as *const i8, c"idx".as_ptr() as *const i8,
            c"wdth".as_ptr() as *const i8, c"hght".as_ptr() as *const i8,
            c"flgs".as_ptr() as *const i8, c"table".as_ptr() as *const i8,
            c"rowid".as_ptr() as *const i8, c"parent".as_ptr() as *const i8,
            c"fkid".as_ptr() as *const i8, c"busy".as_ptr() as *const i8,
            c"log".as_ptr() as *const i8,
            c"checkpointed".as_ptr() as *const i8,
            c"seq".as_ptr() as *const i8, c"name".as_ptr() as *const i8,
            c"file".as_ptr() as *const i8, c"database".as_ptr() as *const i8,
            c"status".as_ptr() as *const i8,
            c"cache_size".as_ptr() as *const i8,
            c"timeout".as_ptr() as *const i8];
